### ISSUE TITLE
Don't notify pull-requester even if they are an owner

### ISSUE THREAD

**Issue by tobie** [tobie/ganesh#4]
Strategy: pass the whole [payload](https://developer.github.com/v3/activity/events/types/#webhook-payload-example-13) of the WebHook request to `metadata()` and get the pull-requester's handle from `body.pull_request.user.login`.

Remove it from `metadata.owners` when sending the comments

/cc @zcorpan

**Comment by tobie** [comment]
Still hasn't reached the top of my todo lists. Apologies.

**Comment by zcorpan** [comment]
Thanks!

**Comment by tobie** [comment]
@zcorpan long overdue. Apologies.
